import type { SiteData } from "@/lib/site-types";

export const defaultSiteData: SiteData = {
  profile: {
    id: "main",
    name: "Jorge Ferreira",
    headlinePt: "Junior Developer",
    headlineEn: "Junior Developer",
    profileImagePath: "/Profile-Photo.png",
    cvFilePath: "./CV.ENG.pdf",
    locationPt: "Lisboa, Portugal",
    locationEn: "Lisbon, Portugal",
    website: "https://www.jmdaf.dev",
    email: "jmferreira0307@gmail.com",
    phone: "+351 934 597 715",
    yearsOfProgramming: 2,
    projectsDeveloped: 4,
    englishLevel: "B2/C1",
  },
  content: {
    "hero.available": { pt: "Disponivel para trabalhar", en: "Available for work" },
    "hero.title": { pt: "Transformo ideias em", en: "I transform ideas into" },
    "hero.titleHighlight": { pt: "experiencias digitais", en: "digital experiences" },
    "hero.description": {
      pt: "Estudante de Engenharia Informatica apaixonado por Inteligencia Artificial e com experiencia em desenvolvimento web, UX/UI Design e criacao de solucoes inovadoras com impacto real.",
      en: "Computer Engineering student passionate about Artificial Intelligence with experience in web development, UX/UI Design and building innovative solutions with real impact.",
    },
    "hero.cta": { pt: "Entrar em Contacto", en: "Get in Touch" },
    "hero.learnMore": { pt: "Conhecer Mais", en: "Learn More" },
    "hero.yearsOfCode": { pt: "Anos de Codigo", en: "Years of Code" },
    "hero.projects": { pt: "Projetos", en: "Projects" },
    "about.subtitle": { pt: "Conhece-me", en: "Get to know me" },
    "about.title": { pt: "Sobre Mim", en: "About Me" },
    "about.p1": {
      pt: "Sou estudante do 3.o ano de Engenharia Informatica no IADE - Creative University, com um forte interesse em programacao e especial foco em desenvolvimento web.",
      en: "I'm a 3rd year Computer Engineering student at IADE - Creative University, with a strong interest in programming and a special focus on web development.",
    },
    "about.p2": {
      pt: "Tenho experiencia em frontend com Next.js, desenvolvimento Android com Kotlin e bases em backend e bases de dados. Valorizo UX/UI e a criacao de interfaces funcionais e intuitivas.",
      en: "I have experience in frontend with Next.js, Android development with Kotlin and foundations in backend and databases. I value UX/UI and the creation of functional, intuitive interfaces.",
    },
    "about.p3": {
      pt: "Mais recentemente, tenho aprofundado a area de Inteligencia Artificial, integrando estes conhecimentos no meu percurso tecnico para desenvolver solucoes uteis, inovadoras e com impacto.",
      en: "More recently, I have been deepening my knowledge in Artificial Intelligence, integrating it into my technical path to build useful, innovative solutions with impact.",
    },
    "about.yearsOfProgramming": { pt: "Anos de Programacao", en: "Years of Programming" },
    "about.projectsDeveloped": { pt: "Projetos Desenvolvidos", en: "Projects Developed" },
    "about.location": { pt: "Localizacao", en: "Location" },
    "about.languages": { pt: "Linguas", en: "Languages" },
    "about.education": { pt: "Formacao", en: "Education" },
    "skills.subtitle": { pt: "O que sei fazer", en: "What I can do" },
    "skills.title": { pt: "Competencias", en: "Skills" },
    "skills.dailyTech": { pt: "Tecnologias que utilizo diariamente", en: "Technologies I use daily" },
    "experience.subtitle": { pt: "Onde trabalhei", en: "Where I've worked" },
    "experience.title": { pt: "Experiencia Profissional", en: "Professional Experience" },
    "experience.cvQuestion": { pt: "Interessado no meu percurso completo?", en: "Interested in my full background?" },
    "experience.cvEn": { pt: "CV English", en: "CV English" },
    "projects.subtitle": { pt: "O que construi", en: "What I've built" },
    "projects.title": { pt: "Projetos", en: "Projects" },
    "projects.academic": { pt: "Academico", en: "Academic" },
    "projects.viewMore": { pt: "Queres ver mais do meu trabalho?", en: "Want to see more of my work?" },
    "projects.viewGithub": { pt: "Ver GitHub", en: "View GitHub" },
    "education.subtitle": { pt: "Formacao", en: "Background" },
    "education.title": { pt: "Educacao", en: "Education" },
    "education.coursesTitle": { pt: "Conhecimentos Adquiridos", en: "Knowledge Acquired" },
    "contact.subtitle": { pt: "Vamos conversar", en: "Let's talk" },
    "contact.title": { pt: "Contacto", en: "Contact" },
    "contact.getInTouch": { pt: "Entra em contacto", en: "Get in touch" },
    "contact.description": {
      pt: "Estou sempre aberto a novas oportunidades e conversas interessantes. Nao hesites em entrar em contacto.",
      en: "I'm always open to new opportunities and interesting conversations. Don't hesitate to reach out.",
    },
    "contact.findMe": { pt: "Encontra-me nas redes", en: "Find me on social media" },
    "contact.email": { pt: "Email", en: "Email" },
    "contact.phone": { pt: "Telefone", en: "Phone" },
    "contact.website": { pt: "Website", en: "Website" },
    "contact.location": { pt: "Localizacao", en: "Location" },
    "footer.rights": { pt: "Todos os direitos reservados.", en: "All rights reserved." },
    "footer.madeWith": { pt: "Feito com Next.js, Prisma e PostgreSQL", en: "Built with Next.js, Prisma and PostgreSQL" },
    "sidebar.available": { pt: "Disponivel", en: "Available" },
  },
  navigationItems: [
    { id: "nav-home", slug: "home", labelPt: "Inicio", labelEn: "Home", href: "#", visible: true, sortOrder: 1 },
    { id: "nav-about", slug: "about", labelPt: "Sobre", labelEn: "About", href: "#sobre", visible: true, sortOrder: 2 },
    { id: "nav-skills", slug: "skills", labelPt: "Competencias", labelEn: "Skills", href: "#competencias", visible: true, sortOrder: 3 },
    { id: "nav-experience", slug: "experience", labelPt: "Experiencia", labelEn: "Experience", href: "#experiencia", visible: true, sortOrder: 4 },
    { id: "nav-projects", slug: "projects", labelPt: "Projetos", labelEn: "Projects", href: "#projetos", visible: true, sortOrder: 5 },
    { id: "nav-education", slug: "education", labelPt: "Educacao", labelEn: "Education", href: "#educacao", visible: true, sortOrder: 6 },
    { id: "nav-contact", slug: "contact", labelPt: "Contacto", labelEn: "Contact", href: "#contacto", visible: true, sortOrder: 7 },
  ],
  socialLinks: [
    { id: "social-github", platform: "github", label: "GitHub", href: "https://github.com/JMiguelF04", visibleInSidebar: true, visibleInContact: true, visibleInFooter: true, sortOrder: 1 },
    { id: "social-linkedin", platform: "linkedin", label: "LinkedIn", href: "https://www.linkedin.com/in/jorge-ferreira-b2a06930b", visibleInSidebar: true, visibleInContact: true, visibleInFooter: true, sortOrder: 2 },
    { id: "social-email", platform: "email", label: "Email", href: "mailto:jmferreira0307@gmail.com", visibleInSidebar: true, visibleInContact: false, visibleInFooter: true, sortOrder: 3 },
  ],
  contactDetails: [
    { id: "contact-email", type: "email", valuePt: "jmferreira0307@gmail.com", valueEn: "jmferreira0307@gmail.com", href: "mailto:jmferreira0307@gmail.com", sortOrder: 1 },
    { id: "contact-phone", type: "phone", valuePt: "+351 934 597 715", valueEn: "+351 934 597 715", href: "tel:+351934597715", sortOrder: 2 },
    { id: "contact-website", type: "website", valuePt: "www.jmdaf.dev", valueEn: "www.jmdaf.dev", href: "https://www.jmdaf.dev", sortOrder: 3 },
    { id: "contact-location", type: "location", valuePt: "Lisboa, Portugal", valueEn: "Lisbon, Portugal", href: null, sortOrder: 4 },
  ],
  spokenLanguages: [
    { id: "lang-pt", slug: "portuguese", namePt: "Portugues", nameEn: "Portuguese", levelPt: "Nativo", levelEn: "Native", sortOrder: 1 },
    { id: "lang-en", slug: "english", namePt: "Ingles", nameEn: "English", levelPt: "B2/C1", levelEn: "B2/C1", sortOrder: 2 },
  ],
  skillCategories: [
    {
      id: "skills-frontend",
      slug: "frontend",
      labelPt: "Frontend",
      labelEn: "Frontend",
      sortOrder: 1,
      skills: [
        { id: "skill-next", name: "Next.js", level: "Advanced", sortOrder: 1 },
        { id: "skill-react", name: "React", level: "Intermediate", sortOrder: 2 },
        { id: "skill-ts", name: "TypeScript", level: "Intermediate", sortOrder: 3 },
        { id: "skill-tailwind", name: "Tailwind CSS", level: "Intermediate", sortOrder: 4 },
      ],
    },
    {
      id: "skills-backend",
      slug: "backend",
      labelPt: "Backend",
      labelEn: "Backend",
      sortOrder: 2,
      skills: [
        { id: "skill-spring", name: "Java / Spring Boot", level: "Intermediate", sortOrder: 1 },
        { id: "skill-rest", name: "APIs REST", level: "Intermediate", sortOrder: 2 },
        { id: "skill-sql", name: "SQL", level: "Intermediate", sortOrder: 3 },
        { id: "skill-node", name: "Node.js", level: "Advanced", sortOrder: 4 },
        { id: "skill-git", name: "Git & GitHub", level: "Advanced", sortOrder: 5 },
      ],
    },
    {
      id: "skills-ai",
      slug: "ai-ml",
      labelPt: "AI & Machine Learning",
      labelEn: "AI & Machine Learning",
      sortOrder: 3,
      skills: [
        { id: "skill-ai", name: "AI Algorithms", level: "Intermediate", sortOrder: 1 },
        { id: "skill-python", name: "Python (AI/ML)", level: "Intermediate", sortOrder: 2 },
      ],
    },
    {
      id: "skills-mobile",
      slug: "mobile-design",
      labelPt: "Mobile & Design",
      labelEn: "Mobile & Design",
      sortOrder: 4,
      skills: [
        { id: "skill-kotlin", name: "Android (Kotlin)", level: "Intermediate", sortOrder: 1 },
        { id: "skill-compose", name: "Jetpack Compose", level: "Basic", sortOrder: 2 },
        { id: "skill-ux", name: "UX/UI Design", level: "Advanced", sortOrder: 3 },
        { id: "skill-figma", name: "Figma", level: "Advanced", sortOrder: 4 },
      ],
    },
  ],
  dailyTechnologies: [
    { id: "daily-next", name: "Next.js", sortOrder: 1 },
    { id: "daily-react", name: "React", sortOrder: 2 },
    { id: "daily-ts", name: "TypeScript", sortOrder: 3 },
    { id: "daily-python", name: "Python", sortOrder: 4 },
    { id: "daily-tailwind", name: "Tailwind CSS", sortOrder: 5 },
    { id: "daily-git", name: "Git", sortOrder: 6 },
    { id: "daily-figma", name: "Figma", sortOrder: 7 },
    { id: "daily-vscode", name: "VS Code", sortOrder: 8 },
    { id: "daily-vercel", name: "Vercel", sortOrder: 9 },
  ],
  experiences: [
    {
      id: "exp-gco",
      slug: "gco-web-developer",
      rolePt: "Programador Web",
      roleEn: "Web Developer",
      company: "GCO - Ginasio Clube Odivelas",
      periodPt: "Jul 2025 - Nov 2025",
      periodEn: "Jul 2025 - Nov 2025",
      technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "API Integration"],
      current: false,
      sortOrder: 1,
      bullets: [
        { id: "exp-gco-1", textPt: "Desenvolvimento do website gcodivelas.pt utilizando Next.js, em colaboracao com outro developer.", textEn: "Development of the gcodivelas.pt website using Next.js, in collaboration with another developer.", sortOrder: 1 },
        { id: "exp-gco-2", textPt: "Implementacao de componentes frontend responsivos e reutilizaveis, seguindo boas praticas de UI/UX.", textEn: "Implementation of responsive and reusable frontend components, following UI/UX best practices.", sortOrder: 2 },
        { id: "exp-gco-3", textPt: "Construcao de paginas dinamicas e otimizacao de performance atraves de SSR e SSG.", textEn: "Building dynamic pages and performance optimization through SSR and SSG.", sortOrder: 3 },
        { id: "exp-gco-4", textPt: "Integracao de funcionalidades essenciais, organizacao de rotas, gestao de estado e interacao com APIs.", textEn: "Integration of essential features, route organization, state management and API interaction.", sortOrder: 4 },
      ],
    },
    {
      id: "exp-robert-mauser",
      slug: "robert-mauser-intern",
      rolePt: "Estagiario",
      roleEn: "Intern",
      company: "Robert Mauser",
      periodPt: "Fev 2026 - Mar 2026",
      periodEn: "Feb 2026 - Mar 2026",
      technologies: ["Java", "Artificial Intelligence (AI)", "Machine Learning", "NLP"],
      current: false,
      sortOrder: 2,
      bullets: [
        { id: "exp-rm-1", textPt: "Desenvolvi ferramentas de IA com o objetivo de automatizar funcionalidades chave utilizando bibliotecas de modelos de linguagem.", textEn: "Developed AI tools aimed at automating key features using language model libraries.", sortOrder: 1 },
        { id: "exp-rm-2", textPt: "Aprofundei competencias em machine learning e processamento de linguagem natural, contribuindo para projetos inovadores.", textEn: "Enhanced skills in machine learning and natural language processing while contributing to innovative projects.", sortOrder: 2 },
      ],
    },
    {
      id: "exp-europalco",
      slug: "europalco-intern",
      rolePt: "Estagiario",
      roleEn: "Intern",
      company: "Europalco",
      periodPt: "Mar 2026 - Presente",
      periodEn: "Mar 2026 - Present",
      technologies: ["RFID", "Monday.com", "Artificial Intelligence (AI)", "Automation"],
      current: true,
      sortOrder: 3,
      bullets: [
        { id: "exp-eu-1", textPt: "Colaborei num projeto de RFID com o objetivo de otimizar os processos de gestao de stock.", textEn: "Collaborated on an RFID project aimed at optimizing stock management processes.", sortOrder: 1 },
        { id: "exp-eu-2", textPt: "Utilizei o Monday.com para otimizar a organizacao do projeto e melhorar a comunicacao da equipa.", textEn: "Utilized Monday.com to streamline project organization and enhance team communication.", sortOrder: 2 },
        { id: "exp-eu-3", textPt: "Integrei solucoes de IA para automacao no desenvolvimento de websites, melhorando a eficiencia operacional.", textEn: "Integrated AI solutions for automation in website development, improving operational efficiency.", sortOrder: 3 },
      ],
    },
  ],
  projects: [
    { id: "project-gco", slug: "gco", titlePt: "GCO - Ginasio Clube Odivelas", titleEn: "GCO - Ginasio Clube Odivelas", descriptionPt: "Website institucional desenvolvido para o Ginasio Clube Odivelas. Projeto focado em performance, responsividade e experiencia do utilizador.", descriptionEn: "Institutional website developed for Ginasio Clube Odivelas. Project focused on performance, responsiveness and user experience.", technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS"], github: null, demo: "https://gcodivelas.pt", academic: false, sortOrder: 1 },
    { id: "project-portfolio", slug: "portfolio", titlePt: "Portfolio Pessoal", titleEn: "Personal Portfolio", descriptionPt: "O meu portfolio pessoal, desenvolvido com Next.js, Prisma e PostgreSQL.", descriptionEn: "My personal portfolio, built with Next.js, Prisma and PostgreSQL.", technologies: ["Next.js", "React", "TypeScript", "Prisma", "PostgreSQL"], github: "https://github.com/JMiguelF04/portfolio", demo: null, academic: false, sortOrder: 2 },
    { id: "project-around-me", slug: "around-me", titlePt: "Around Me", titleEn: "Around Me", descriptionPt: "Plataforma web para descoberta de entretenimento noturno com mapa interativo, check-in e recomendacoes personalizadas.", descriptionEn: "Web platform for nightlife discovery with an interactive map, check-in flow and personalized recommendations.", technologies: ["Next.js", "TypeScript", "SQL", "QGIS", "Figma"], github: "https://github.com/antmmatos/Around-Me", demo: null, academic: true, sortOrder: 3 },
    { id: "project-glup", slug: "glup", titlePt: "Glup - Rastreamento de Hidratacao", titleEn: "Glup - Hydration Tracking", descriptionPt: "Aplicacao movel Android para monitorizacao do consumo diario de agua com metas personalizadas, graficos e recompensas.", descriptionEn: "Android app for daily water tracking with personalized goals, charts and rewards.", technologies: ["Kotlin", "Java", "Android Studio", "SQL", "REST API"], github: "https://github.com/JMiguelF04/ProjetoAPP_Grupo7_D02_Iade", demo: null, academic: true, sortOrder: 4 },
  ],
  educationEntries: [
    {
      id: "edu-iade",
      slug: "iade-computer-engineering",
      degreePt: "Licenciatura em Engenharia Informatica",
      degreeEn: "Bachelor's in Computer Engineering",
      institution: "IADE - Creative University",
      periodPt: "2023 - Presente",
      periodEn: "2023 - Present",
      descriptionPt: "Formacao abrangente em ciencias da computacao com foco pratico em desenvolvimento de software.",
      descriptionEn: "Comprehensive training in computer science with a practical focus on software development.",
      sortOrder: 1,
      highlights: [
        { id: "edu-1", textPt: "Desenvolvimento web com Next.js e TypeScript", textEn: "Web development with Next.js and TypeScript", sortOrder: 1 },
        { id: "edu-2", textPt: "Competencias em UX/UI Design e criacao de interfaces funcionais", textEn: "UX/UI Design skills and creation of functional interfaces", sortOrder: 2 },
        { id: "edu-3", textPt: "Desenvolvimento de aplicacoes moveis (Android/Kotlin)", textEn: "Mobile app development (Android/Kotlin)", sortOrder: 3 },
        { id: "edu-4", textPt: "Backend com Java / Spring Boot", textEn: "Backend with Java / Spring Boot", sortOrder: 4 },
        { id: "edu-5", textPt: "Programacao em C e bases solidas de SQL", textEn: "C programming and solid SQL foundations", sortOrder: 5 },
        { id: "edu-6", textPt: "Formacao em Sistemas Distribuidos e Algoritmos de IA", textEn: "Training in Distributed Systems and AI Algorithms", sortOrder: 6 },
      ],
    },
  ],
};
